using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class GlobalNumericVariables
{

    //WHEN ADDING A VARIABLE, DO NOT FORGET TO ADD IT IN THE CONSTRUCTOR !!!!!!!
    //MODIFY ONLY IN THE CONSTRUCTOR !!!

    public float DOUBLE_CLICK_INTERVAL;

    public int STARTING_MONEY;
    public float STARTING_REPUTATION;
    public float STARTING_INFLUENCE;
    public float STARTING_CONNECTION;
    public int STARTING_DAY;
    public int STARTING_ASSISTANT_POINTS;

    public int DAILY_RENT;

    public int BASIC_GIRL_DAY_COST;
    public float GIRL_DAY_COST_POPULARITY_MULTIPLIER;
    public float DAY_COST_RANDOM_RANGE_PERCENTAGE;

    public int BASIC_DAY_EARNINGS;
    public float DAY_EARNINGS_RANDOM_RANGE_PERCENTAGE;

    public float BOOTH_GAME_TIMER_HELP;
    public float BOOTH_GAME_TIMER_HELP_RANDOM_RANGE;
    public float BOOTH_GAME_BASIC_BOOTH_TIME;
    public float BOOTH_GAME_BASIC_FINISH_TIME;
    public int BOOTH_GAME_WORK_XP_VALUE;
    public int BOOTH_GAME_WORK_XP_RANDOM_RANGE_MIN;
    public int BOOTH_GAME_WORK_XP_RANDOM_RANGE_MAX;
    public int BOOTH_GAME_WORK_XP_RANDOM_RANGE_VALUE_TO_REACH;

    public float BOOTH_GAME_MIN_HAPPINESS_FOR_EXTEND;

    public float BOOTH_GAME_TIME;

    public int NUMBER_OF_BOOTHS;
    public int MAX_NUMBER_OF_BOOTHS;

    public float CURRENT_CLIENT_GENERATOR_TIMER;
    public float BASIC_CLIENT_GENERATOR_RANDOM_RANGE;

    public float ASK_HELP_TIMER;

    public float EARN_MONEY_TIMER;
    public int EARN_MONEY_DANCE_AMOUNT;
    public int EARN_MONEY_POSE_AMOUNT;
    public int EARN_MONEY_FOREPLAY_AMOUNT;
    public int EARN_MONEY_ORAL_AMOUNT;
    public int EARN_MONEY_SEX_AMOUNT;
    public int EARN_MONEY_GROUP_AMOUNT;

    public int EARN_MONEY_DANCE_INCREASE;
    public int EARN_MONEY_POSE_INCREASE;
    public int EARN_MONEY_FOREPLAY_INCREASE;
    public int EARN_MONEY_ORAL_INCREASE;
    public int EARN_MONEY_SEX_INCREASE;
    public int EARN_MONEY_GROUP_INCREASE;

    public float EARN_MONEY_HAPPINESS_MULTIPLIER;
    public float EARN_MONEY_POPULARITY_MULTIPLIER;
    public float EARN_MONEY_VERY_POOR_CLIENT_MULTIPLIER;
    public float EARN_MONEY_POOR_CLIENT_MULTIPLIER;
    public float EARN_MONEY_BELOW_AVERAGE_CLIENT_MULTIPLIER;
    public float EARN_MONEY_AVERAGE_CLIENT_MULTIPLIER;
    public float EARN_MONEY_ABOVE_AVERAGE_CLIENT_MULTIPLIER;
    public float EARN_MONEY_RICH_CLIENT_MULTIPLIER;
    public float EARN_MONEY_VERY_RICH_CLIENT_MULTIPLIER;
    public float EARN_MONEY_MEGA_RICH_CLIENT_MULTIPLIER;
    public float EARN_MONEY_CORRECT_FINISHER_MULTIPLIER;
    public float EARN_MONEY_GIRL_ENERGY_LOST;
    public float EARN_MONEY_GIRL_ENERGY_LOST_MODIFICATOR;
    public float EARN_MONEY_GIRL_CUT_MULTIPLIER;

    public float EARN_MONEY_GIRL_SKILL_MULTIPLIER;

    public int EARN_MONEY_GIRL_POPULARITY_GAIN;

    public float EARN_MONEY_GENERIC_MULTIPLIER;

    public float EARN_MONEY_DRINK_HAPPINESS_BOOST;
    public float EARN_MONEY_CIGARETTES_HAPPINESS_BOOST;
    public float EARN_MONEY_DRUG_HAPPINESS_BOOST;
    public float EARN_MONEY_CONDOM_HAPPINESS_BOOST;

    public float IMPROVEMENT_HAPPINESS_BOOST;

    public float EARN_OPENNESS_TIMER;
    public float EARN_OPENNESS_AMOUNT;

    public int INFLUENCE_GAIN;
    public int CONNECTION_GAIN;
    public int INFLUENCE_LOST;
    public int CONNECTION_LOST;

    public float INFLUENCE_GAIN_RATIO;

    public float BASIC_REPUTATION_GAIN;
    public float REPUTATION_GAIN;

    public float CLIENT_HAPPINESS_INCREASE_MULTIPLIER;

    public float CLIENT_END_WITHOUT_GIRL_POPULARITY_DROP;
    public int CLIENT_CORRECT_HELP_HAPPINESS_BOOST;
    public int CLIENT_INCORRECT_HELP_HAPPINESS_LOST;
    public float CLIENT_BASE_HAPPINESS_GAIN;
    public float CLIENT_CREATION_HAPPINESS_MIN;
    public float CLIENT_CREATION_HAPPINESS_MAX;

    public int REPUTATION_MIN;
    public int REPUTATION_MAX;

    public float DANCE_POLICIES_MULTIPLIER;
    public float DANCE_POLICIES_INCREASE;

    public float POSE_POLICIES_MULTIPLIER;
    public float POSE_POLICIES_INCREASE;

    public float FOREPLAY_POLICIES_MULTIPLIER;
    public float FOREPLAY_POLICIES_INCREASE;

    public float ORAL_POLICIES_MULTIPLIER;
    public float ORAL_POLICIES_INCREASE;

    public float SEX_POLICIES_MULTIPLIER;
    public float SEX_POLICIES_INCREASE;

    public float GROUP_POLICIES_MULTIPLIER;
    public float GROUP_POLICIES_INCREASE;

    public float FACIAL_POLICIES_MULTIPLIER;
    public float FACIAL_POLICIES_INCREASE;

    public float BODY_POLICIES_MULTIPLIER;
    public float BODY_POLICIES_INCREASE;

    public float INSIDE_POLICIES_MULTIPLIER;
    public float INSIDE_POLICIES_INCREASE;

    public float CHANCE_CLIENT_IS_CRIMINAL;
    public float CHANCE_CLIENT_IS_POLICE;

    public int NEW_BOOTH_PRICE;
    public int BAR_PRICE;
    public int KITCHEN_PRICE;
    public int PHARMACY_PRICE;
    public int CONDOM_DISPENSERS_PRICE;
    public int STAGE_PRICE;
    public int TRAINING_ZONE_PRICE;
    public int TRAINING_ZONE_DANCE_PRICE;
    public int TRAINING_ZONE_POSE_PRICE;
    public int TRAINING_ZONE_FOREPLAY_PRICE;
    public int TRAINING_ZONE_ORAL_PRICE;
    public int TRAINING_ZONE_SEX_PRICE;
    public int TRAINING_ZONE_GROUP_PRICE;
    public int DRESSING_ROOM_PRICE;
    public int DRESSING_ROOM_PILLOWS_PRICE;
    public int DRESSING_ROOM_LOUNGE_CHAIR_PRICE;
    public int DRESSING_ROOM_COUCH_PRICE;
    public int DRESSING_ROOM_BED_PRICE;
    public int DRESSING_ROOM_KING_SIZE_BED_PRICE;
    public int SIGN_PRICE;
    public int ON_LINE_ADS_CAMPAIGN_PRICE;
    public int FLYER_AD_CAMPAIGN_PRICE;
    public int LIVE_AD_CAMPAIGN_PRICE;
    public int SEXY_COSTUME_PRICE;
    public int BUNNY_COSTUME_PRICE;
    public int MAID_COSTUME_PRICE;
    public int NURSE_COSTUME_PRICE;

    public float BASIC_TRAINING_MULTIPLIER;
    public float TRAINING_MULTIPLIER;
    public float DANCE_TRAINING_MULTIPLIER;
    public float POSE_TRAINING_MULTIPLIER;
    public float FOREPLAY_TRAINING_MULTIPLIER;
    public float ORAL_TRAINING_MULTIPLIER;
    public float SEX_TRAINING_MULTIPLIER;
    public float GROUP_TRAINING_MULTIPLIER;

    public int REST_ENERGY_GAIN;

    public int MAX_ENERGY;
    public int MAX_ENERGY_GAIN;
    public int MIN_ENERGY;

    public float BASIC_ASK_HELP_BONUS_MULTIPLIER;
    public float ASK_HELP_BONUS_MULTIPLIER;

    public float MIN_OPENNESS_DANCE;
    public float MIN_OPENNESS_POSE;
    public float MIN_OPENNESS_FOREPLAY;
    public float MIN_OPENNESS_ORAL;
    public float MIN_OPENNESS_SEX;
    public float MIN_OPENNESS_GROUP;

    public float MIN_OPENNESS_SOLO_FINGERING;
    public float MIN_OPENNESS_TOYS_MASTURBATION;

    public float MIN_OPENNESS_FOOTJOB;
    public float MIN_OPENNESS_TITSJOB;



    public float MIN_OPENNESS_BODY_FINISH;
    public float MIN_OPENNESS_FACIAL_FINISH;
    public float MIN_OPENNESS_INSIDE_FINISH;
    public float MIN_OPENNESS_INSIDE_ANAL_FINISH;
    public float MIN_OPENNESS_SWALLOW_FINISH;
    public float MIN_OPENNESS_TITS_FINISH;
    public float MIN_OPENNESS_DOUBLE_FINISH;
    public float MIN_OPENNESS_TRIPLE_FINISH;

    public int MAX_SAVE_SLOTS;


    //The index of the scene currently being played in the tutorial
    //e.g. the scene 0 of the tutorial is on the club, the scene 1 is on the recruitment screen, etc...
    public int TUTORIAL_SCENE_STEP_NUMBER;

    public float CLIENT_HAPPINESS_TRANSFER_RATIO;


    public float[] INTERACTION_DURATION_INCREASE_COSTUME_EFFECT;
    public float[] EARNINGS_INCREASE_COSTUME_EFFECT;
    public float[] HELP_BONUS_INCREASE_COSTUME_EFFECT;
    public int[] SKILL_GAIN_INCREASE_COSTUME_EFFECT;

    public float[] NAKED_INTERACTION_INCREASE_COSTUME_EFFECT;
    public float[] NAKED_EARNINGS_INCREASE_COSTUME_EFFECT;
    public float[] NAKED_HELP_BONUS_INCREASE_COSTUME_EFFECT;
    public int[] NAKED_SKILL_GAIN_INCREASE_COSTUME_EFFECT;
    public float[] NAKED_ENERGY_LOST_DECREASE_COSTUME_EFFECT;
    public float[] NAKED_REPUTATION_GAIN_COSTUME_EFFECT;
    public float[] NAKED_EVENT_CHANCE_INCREASE_COSTUME_EFFECT;

    public float[] ENERGY_LOST_DECREASE_COSTUME_EFFECT;
    public float[] REPUTATION_GAIN_COSTUME_EFFECT;
    public float[] EVENT_CHANCE_INCREASE_COSTUME_EFFECT;

    public int MAX_STATS_VALUE;
    public int MIN_STATS_VALUE;

    public int MAX_POPULARITY_VALUE;
    public int MIN_POPULARITY_VALUE;

    public float MAX_OPENNESS_VALUE;
    public float MIN_OPENNESS_VALUE;

    //Money the day before going to booth game
    public int MONEY_BEFORE;
    public float REPUTATION_BEFORE;

    public SortType SORT_TYPE;

    public int EVENT_CHANCE;
    public int EVENT_CHANCE_MAX;

    public float MAX_CLIENT_HAPPINESS;
    public float MIN_CLIENT_HAPPINESS;

    public int MAX_WORKING_GIRLS;

    public int COSTUME_LEVEL;

    public int CLUB_LEVEL;

    public float MIN_AFFECTION;
    public float MAX_AFFECTION;

    public float INTERACTION_AFFECTION_GAIN;
    public float INTERACTION_AFFECTION_GAIN_INCREASE;

    public float INTERACTION_OPENNESS_GAIN;
    public float INTERACTION_OPENNESS_GAIN_INCREASE;

    public int MAX_TALKS_PER_DAY;
    public int MAX_TALKS_PER_DAY_INCREASE;

    public int FIRST_MISSION_ID;
    public int SECOND_MISSION_ID;
    public int THIRD_MISSION_ID;
    public int FOURTH_MISSION_ID;
    public int UNLOCK_ANY_SERVICE_MISSION_ID;

    public int END_OF_CONTENT_DIALOG_ID;
    public int DAY_RECAP_DIALOG_ID;
    public int TUTORIAL_OPEN_DIALOG_ID;
    public int TUTORIAL_CLOSE_DIALOG_ID;
    public int FIRST_MISION_OPEN_DIALOG_ID;
    public int FIRST_MISION_CLOSE_DIALOG_ID;
    public int SECOND_MISION_OPEN_DIALOG_ID;
    public int SECOND_MISION_CLOSE_DIALOG_ID;
    public int THIRD_MISION_OPEN_DIALOG_ID;
    public int THIRD_MISION_CLOSE_DIALOG_ID;
    public int FOURTH_MISION_OPEN_DIALOG_ID;
    public int FOURTH_MISION_MIDDLE_DIALOG_ID;
    public int FOURTH_MISION_CLOSE_DIALOG_ID;
    public int FIFTH_MISION_OPEN_DIALOG_ID;
    public int FIFTH_MISION_CLOSE_DIALOG_ID;
    public int UNLOCK_ANY_SERVICE_MISSION_CLOSE_DIALOG_ID;
    public int ASSISTANT_FIRST_LATE_NIGHT_MEETING_DIALOG_ID;
    public int ASSISTANT_SECOND_LATE_NIGHT_MEETING_DIALOG_ID;
    public int ASSISTANT_THIRD_LATE_NIGHT_MEETING_DIALOG_ID;
    public int ASSISTANT_FIRST_CAFE_DATE_DIALOG_ID;
    public int ASSISTANT_UNLOCK_BASIC_DANCE_DIALOG_ID;
    public int ASSISTANT_UNLOCK_CLOSER_DANCE_DIALOG_ID;
    public int ASSISTANT_UNLOCK_TOPLESS_DANCE_DIALOG_ID;
    public int ASSISTANT_UNLOCK_POSE_NAKED_DIALOG_ID;
    public int ASSISTANT_UNLOCK_SOLO_FINGERING_DIALOG_ID;
    public int ASSISTANT_UNLOCK_TOYS_MASTURBATION_DIALOG_ID;
    public int ASSISTANT_UNLOCK_HANDJOB_DIALOG_ID;
    public int ASSISTANT_UNLOCK_FOOTJOB_DIALOG_ID;
    public int ASSISTANT_UNLOCK_TITSJOB_DIALOG_ID;
    public int ASSISTANT_UNLOCK_TENNIS_DATE_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FIRST_VIDEO_UNLOCK_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FIRST_VIDEO_UNLOCK_PART_2_DIALOG_ID;
    public int ASSISTANT_DATE_VIDEO_TOKEN_AVAILABLE_DIALOG_ID;

    public int ASSISTANT_BAR_DATE_SECOND_VIDEO_UNLOCK_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_SECOND_VIDEO_UNLOCK_PART_2_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_THIRD_VIDEO_UNLOCK_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_THIRD_VIDEO_UNLOCK_PART_2_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_PART_2_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_PART_3_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_PART_2_DIALOG_ID;
    public int ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_PART_3_DIALOG_ID;

    public int CRIME_SERVICE_TUTORIAL_DIALOG_ID;
    public int CRIME_SERVICE_TUTORIAL_DIALOG_CLOSE_ID;

    public int CRIME_SERVICE_SELECT_FEW_ID;
    public int CRIME_SERVICE_GIFTS_CIGARETTES_ID;
    public int CRIME_SERVICE_GIFTS_CONDOMS_ID;
    public int CRIME_SERVICE_GIFTS_DRINKS_ID;
    public int CRIME_SERVICE_GIFTS_DRUGS_ID;
    public int CRIME_SERVICE_PATRONAGE_ID;
    public int CRIME_SERVICE_NEGOTIATOR_ID;
    public int CRIME_SERVICE_LOTTERY_ID;
    public int CRIME_SERVICE_COACH_ID;
    public int CRIME_SERVICE_RELAXER_ID;

    public float SELECT_FEW_QUALITY_MULTIPLIER;
    public float PATRONAGE_CHANCE_MULTIPLIER;
    public int NEGOTIATOR_MAX_USAGE;
    public int NEGOTIATOR_PER_USAGE_MULTIPLIER;
    public float COACH_EARNINGS_MULTIPLIER;
    public float COACH_ENERGY_LOST_MULTIPLIER;
    public float RELAXER_EARNINGS_MULTIPLIER;
    public float RELAXER_ENERGY_LOST_MULTIPLIER;

    public int FIRST_LATE_NIGHT_MEETING_DAY;
    public int SECOND_LATE_NIGHT_MEETING_DAY_DELAY;

    public float DATE_GAME_TIME;

    public int DATE_GAME_MAX_SCORE;
    public int DATE_GAME_MAX_SCORE_INCREASE;

    public int DATE_GAME_MIN_EARNT_SCORE;
    public int DATE_GAME_MAX_HP;

    public int CAFE_DATE_ID;

    public int MONEY_TO_NICOLE_POINTS_CONVERSION_VALUE;

    public int MINIMUM_POINTS_EARNED_PER_DATE;
    public int MINIMUM_POINTS_KEPT_PER_DATE;
    public int MINIMUM_POINTS_EARNED_PER_DATE_INCREASE;

    public int MINIMUM_DATES_PER_DAY;

    public int PERSONAL_IMPROVEMENT_STORE_LEVEL;

    public float DATE_GAME_SPEED_MULTIPLIER;
    public float DATE_GAME_SPEED_MULTIPLIER_MODIFIER;

    public int DATE_GAME_BETTER_SCORE_OBSTACLE_VALUE;
    public int DATE_GAME_SCORE_STREAK_TO_REACH_FOR_VIDEO_TOKEN;

    //WHEN ADDING A VARIABLE, DO NOT FORGET TO ADD IT IN THE CONSTRUCTOR !!!!!!!
    //MODIFY ONLY IN THE CONSTRUCTOR !!!

    public GlobalNumericVariables()
    {
        DOUBLE_CLICK_INTERVAL = 0.4f;

        STARTING_MONEY = 300;
        STARTING_REPUTATION = 0f;
        STARTING_INFLUENCE = 0f;
        STARTING_CONNECTION = 0f;
        STARTING_DAY = 1;
        STARTING_ASSISTANT_POINTS = 0;

        DAILY_RENT = 50;

        BASIC_GIRL_DAY_COST = 10;
        GIRL_DAY_COST_POPULARITY_MULTIPLIER = 1f;
        DAY_COST_RANDOM_RANGE_PERCENTAGE = 10f;

        BASIC_DAY_EARNINGS = 5;
        DAY_EARNINGS_RANDOM_RANGE_PERCENTAGE = 50f;

        BOOTH_GAME_TIMER_HELP = 5f;
        BOOTH_GAME_TIMER_HELP_RANDOM_RANGE = 3f;
        BOOTH_GAME_BASIC_BOOTH_TIME = 20f;
        BOOTH_GAME_BASIC_FINISH_TIME = 15f;
        BOOTH_GAME_WORK_XP_VALUE = 1;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_MIN = 0;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_MAX = 100;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_VALUE_TO_REACH = 90;

        BOOTH_GAME_MIN_HAPPINESS_FOR_EXTEND = 60f;

        BOOTH_GAME_TIME = 60f;

        NUMBER_OF_BOOTHS = 2;
        MAX_NUMBER_OF_BOOTHS = 6;

        CURRENT_CLIENT_GENERATOR_TIMER = 10f;
        BASIC_CLIENT_GENERATOR_RANDOM_RANGE = 2f;

        ASK_HELP_TIMER = 10f;

        EARN_MONEY_TIMER = 1f;
        EARN_MONEY_DANCE_AMOUNT = 12;
        EARN_MONEY_POSE_AMOUNT = 13;
        EARN_MONEY_FOREPLAY_AMOUNT = 14;
        EARN_MONEY_ORAL_AMOUNT = 15;
        EARN_MONEY_SEX_AMOUNT = 16;
        EARN_MONEY_GROUP_AMOUNT = 17;

        EARN_MONEY_DANCE_INCREASE = 1;
        EARN_MONEY_POSE_INCREASE = 1;
        EARN_MONEY_FOREPLAY_INCREASE = 1;
        EARN_MONEY_ORAL_INCREASE = 1;
        EARN_MONEY_SEX_INCREASE = 1;
        EARN_MONEY_GROUP_INCREASE = 1;

        EARN_MONEY_HAPPINESS_MULTIPLIER = 0.1f;
        EARN_MONEY_POPULARITY_MULTIPLIER = 0.1f;
        EARN_MONEY_VERY_POOR_CLIENT_MULTIPLIER = 0.4f;
        EARN_MONEY_POOR_CLIENT_MULTIPLIER = 0.5f;
        EARN_MONEY_BELOW_AVERAGE_CLIENT_MULTIPLIER = 0.6f;
        EARN_MONEY_AVERAGE_CLIENT_MULTIPLIER = 0.7f;
        EARN_MONEY_ABOVE_AVERAGE_CLIENT_MULTIPLIER = 0.8f;
        EARN_MONEY_RICH_CLIENT_MULTIPLIER = 0.9f;
        EARN_MONEY_VERY_RICH_CLIENT_MULTIPLIER = 1.0f;
        EARN_MONEY_MEGA_RICH_CLIENT_MULTIPLIER = 1.1f;
        EARN_MONEY_CORRECT_FINISHER_MULTIPLIER = 2f;
        EARN_MONEY_GIRL_ENERGY_LOST = 1f;
        EARN_MONEY_GIRL_ENERGY_LOST_MODIFICATOR = 0.1f;
        EARN_MONEY_GIRL_CUT_MULTIPLIER = 0.2f;

        EARN_MONEY_GIRL_SKILL_MULTIPLIER = 0.15f;

        EARN_MONEY_GIRL_POPULARITY_GAIN = 1;

        EARN_MONEY_GENERIC_MULTIPLIER = 1f;

        EARN_MONEY_DRINK_HAPPINESS_BOOST = 20f;
        EARN_MONEY_CIGARETTES_HAPPINESS_BOOST = 20f;
        EARN_MONEY_DRUG_HAPPINESS_BOOST = 20f;
        EARN_MONEY_CONDOM_HAPPINESS_BOOST = 20f;

        IMPROVEMENT_HAPPINESS_BOOST = 5f;

        EARN_OPENNESS_TIMER = 1f;
        EARN_OPENNESS_AMOUNT = 0.07f;

        INFLUENCE_GAIN = 1;
        CONNECTION_GAIN = 1;
        INFLUENCE_LOST = 1;
        CONNECTION_LOST = 1;

        INFLUENCE_GAIN_RATIO = 0.02f;

        BASIC_REPUTATION_GAIN = 1f;
        REPUTATION_GAIN = 1f;

        CLIENT_HAPPINESS_INCREASE_MULTIPLIER = 0.025f;

        CLIENT_END_WITHOUT_GIRL_POPULARITY_DROP = 5f;
        CLIENT_CORRECT_HELP_HAPPINESS_BOOST = 15;
        CLIENT_INCORRECT_HELP_HAPPINESS_LOST = 20;
        CLIENT_BASE_HAPPINESS_GAIN = 0.1f;
        CLIENT_CREATION_HAPPINESS_MIN = 40f;
        CLIENT_CREATION_HAPPINESS_MAX = 50f;

        REPUTATION_MIN = 0;
        REPUTATION_MAX = 100;

        DANCE_POLICIES_MULTIPLIER = 0.8f;
        DANCE_POLICIES_INCREASE = 0.1f;

        POSE_POLICIES_MULTIPLIER = 0.8f;
        POSE_POLICIES_INCREASE = 0.1f;

        FOREPLAY_POLICIES_MULTIPLIER = 0.8f;
        FOREPLAY_POLICIES_INCREASE = 0.1f;

        ORAL_POLICIES_MULTIPLIER = 0.8f;
        ORAL_POLICIES_INCREASE = 0.1f;

        SEX_POLICIES_MULTIPLIER = 0.8f;
        SEX_POLICIES_INCREASE = 0.1f;

        GROUP_POLICIES_MULTIPLIER = 0.8f;
        GROUP_POLICIES_INCREASE = 0.1f;

        FACIAL_POLICIES_MULTIPLIER = 0.8f;
        FACIAL_POLICIES_INCREASE = 0.1f;

        BODY_POLICIES_MULTIPLIER = 0.8f;
        BODY_POLICIES_INCREASE = 0.1f;

        INSIDE_POLICIES_MULTIPLIER = 0.8f;
        INSIDE_POLICIES_INCREASE = 0.1f;

        CHANCE_CLIENT_IS_CRIMINAL = 0.2f;
        CHANCE_CLIENT_IS_POLICE = 0.1f;

        NEW_BOOTH_PRICE = 100;
        BAR_PRICE = 100;
        KITCHEN_PRICE = 100;
        PHARMACY_PRICE = 100;
        CONDOM_DISPENSERS_PRICE = 100;
        STAGE_PRICE = 100;
        TRAINING_ZONE_PRICE = 100;
        TRAINING_ZONE_DANCE_PRICE = 100;
        TRAINING_ZONE_POSE_PRICE = 100;
        TRAINING_ZONE_FOREPLAY_PRICE = 100;
        TRAINING_ZONE_ORAL_PRICE = 100;
        TRAINING_ZONE_SEX_PRICE = 100;
        TRAINING_ZONE_GROUP_PRICE = 100;
        DRESSING_ROOM_PRICE = 100;
        DRESSING_ROOM_PILLOWS_PRICE = 100;
        DRESSING_ROOM_LOUNGE_CHAIR_PRICE = 100;
        DRESSING_ROOM_COUCH_PRICE = 100;
        DRESSING_ROOM_BED_PRICE = 100;
        DRESSING_ROOM_KING_SIZE_BED_PRICE = 100;
        SIGN_PRICE = 100;
        ON_LINE_ADS_CAMPAIGN_PRICE = 100;
        FLYER_AD_CAMPAIGN_PRICE = 100;
        LIVE_AD_CAMPAIGN_PRICE = 100;
        SEXY_COSTUME_PRICE = 100;
        BUNNY_COSTUME_PRICE = 100;
        MAID_COSTUME_PRICE = 100;
        NURSE_COSTUME_PRICE = 100;

        BASIC_TRAINING_MULTIPLIER = 1f;
        TRAINING_MULTIPLIER = 1f;
        DANCE_TRAINING_MULTIPLIER = 0f;
        POSE_TRAINING_MULTIPLIER = 0f;
        FOREPLAY_TRAINING_MULTIPLIER = 0f;
        ORAL_TRAINING_MULTIPLIER = 0f;
        SEX_TRAINING_MULTIPLIER = 0f;
        GROUP_TRAINING_MULTIPLIER = 0f;

        REST_ENERGY_GAIN = 25;

        MAX_ENERGY = 100;
        MAX_ENERGY_GAIN = 5;
        MIN_ENERGY = 0;

        BASIC_ASK_HELP_BONUS_MULTIPLIER = 1f;
        ASK_HELP_BONUS_MULTIPLIER = 1f;

        MIN_OPENNESS_DANCE = 0f;
        MIN_OPENNESS_POSE = 16.6f;
        MIN_OPENNESS_FOREPLAY = 33.2f;
        MIN_OPENNESS_ORAL = 49.8f;
        MIN_OPENNESS_SEX = 66.4f;
        MIN_OPENNESS_GROUP = 83f;

        MIN_OPENNESS_SOLO_FINGERING = 22.1f;
        MIN_OPENNESS_TOYS_MASTURBATION = 27.6f;

        MIN_OPENNESS_FOOTJOB = 38.7f;
        MIN_OPENNESS_TITSJOB = 44.2f;

        MIN_OPENNESS_BODY_FINISH = 33.2f;
        MIN_OPENNESS_FACIAL_FINISH = 49.8f;
        MIN_OPENNESS_INSIDE_FINISH = 71.9f;
        MIN_OPENNESS_INSIDE_ANAL_FINISH = 83f;
        MIN_OPENNESS_SWALLOW_FINISH = 60.8f;
        MIN_OPENNESS_TITS_FINISH = 44.2f;
        MIN_OPENNESS_DOUBLE_FINISH = 88.5f;
        MIN_OPENNESS_TRIPLE_FINISH = 94f;

        MAX_SAVE_SLOTS = 100;


        //The index of the scene currently being played in the tutorial
        //e.g. the scene 0 of the tutorial is on the club, the scene 1 is on the recruitment screen, etc...
        TUTORIAL_SCENE_STEP_NUMBER = 0;

        CLIENT_HAPPINESS_TRANSFER_RATIO = 0.006f;

        INTERACTION_DURATION_INCREASE_COSTUME_EFFECT = new float[3]{ 1.25f, 1.5f, 1.75f };
        EARNINGS_INCREASE_COSTUME_EFFECT = new float[3] { 1.2f, 1.4f,1.6f};
        HELP_BONUS_INCREASE_COSTUME_EFFECT = new float[3] { 1.5f,2f,2.5f};
        SKILL_GAIN_INCREASE_COSTUME_EFFECT = new int[3] {10 , 15, 20};

        NAKED_INTERACTION_INCREASE_COSTUME_EFFECT = new float[3] { 1.1f, 1.2f, 1.3f };
        NAKED_EARNINGS_INCREASE_COSTUME_EFFECT = new float[3] { 1.05f, 1.1f, 1.15f };
        NAKED_HELP_BONUS_INCREASE_COSTUME_EFFECT = new float[3] { 1.2f,1.4f,1.6f };
        NAKED_SKILL_GAIN_INCREASE_COSTUME_EFFECT = new int[3] { 3, 5, 7 };
        NAKED_ENERGY_LOST_DECREASE_COSTUME_EFFECT = new float[3] { 0.95f, 0.9f, 0.85f };
        NAKED_REPUTATION_GAIN_COSTUME_EFFECT = new float[3] { 1.2f, 1.4f, 1.6f };
        NAKED_EVENT_CHANCE_INCREASE_COSTUME_EFFECT = new float[3] { 3f, 6f, 9f };

        ENERGY_LOST_DECREASE_COSTUME_EFFECT = new float[3] { 0.8f, 0.6f, 0.4f };
        REPUTATION_GAIN_COSTUME_EFFECT = new float[3] { 1.5f, 2f, 2.5f };
        EVENT_CHANCE_INCREASE_COSTUME_EFFECT = new float[3] { 2f, 3f, 4f };

        MAX_STATS_VALUE = 100;
        MIN_STATS_VALUE = 0;

        MAX_POPULARITY_VALUE = 100;
        MIN_POPULARITY_VALUE = 0;

        MAX_OPENNESS_VALUE = 100f;
        MIN_OPENNESS_VALUE = 0f;

        MONEY_BEFORE = 0;
        REPUTATION_BEFORE = 0f;

        SORT_TYPE = SortType.NAME;

        EVENT_CHANCE = 20;
        EVENT_CHANCE_MAX = 100;

        MAX_CLIENT_HAPPINESS = 100f;
        MIN_CLIENT_HAPPINESS = 0f;

        MAX_WORKING_GIRLS = 8;

        COSTUME_LEVEL = -1;

        CLUB_LEVEL = 0;

        MIN_AFFECTION = 0f;
        MAX_AFFECTION = 100f;

        INTERACTION_AFFECTION_GAIN = 1f;
        INTERACTION_AFFECTION_GAIN_INCREASE = 1f;

        INTERACTION_OPENNESS_GAIN = 1f;
        INTERACTION_OPENNESS_GAIN_INCREASE = 1f;

        MAX_TALKS_PER_DAY = 1;
        MAX_TALKS_PER_DAY_INCREASE = 1;

        FIRST_MISSION_ID = 0;
        SECOND_MISSION_ID = 1;
        THIRD_MISSION_ID = 2;
        FOURTH_MISSION_ID = 3;
        UNLOCK_ANY_SERVICE_MISSION_ID = 4;

        END_OF_CONTENT_DIALOG_ID = -10;
        DAY_RECAP_DIALOG_ID = -1;
        TUTORIAL_OPEN_DIALOG_ID = 0;
        TUTORIAL_CLOSE_DIALOG_ID = 1;
        FIRST_MISION_OPEN_DIALOG_ID = 2;
        FIRST_MISION_CLOSE_DIALOG_ID = 3;
        SECOND_MISION_OPEN_DIALOG_ID = 4;
        SECOND_MISION_CLOSE_DIALOG_ID = 5;
        THIRD_MISION_OPEN_DIALOG_ID = 6;
        THIRD_MISION_CLOSE_DIALOG_ID = 7;
        FOURTH_MISION_OPEN_DIALOG_ID = 8;
        FOURTH_MISION_MIDDLE_DIALOG_ID = 9;
        FOURTH_MISION_CLOSE_DIALOG_ID = 10;
        FIFTH_MISION_OPEN_DIALOG_ID = 11;
        FIFTH_MISION_CLOSE_DIALOG_ID = 12;
        UNLOCK_ANY_SERVICE_MISSION_CLOSE_DIALOG_ID = 13;
        ASSISTANT_FIRST_LATE_NIGHT_MEETING_DIALOG_ID = 14;
        ASSISTANT_SECOND_LATE_NIGHT_MEETING_DIALOG_ID = 15;
        ASSISTANT_THIRD_LATE_NIGHT_MEETING_DIALOG_ID = 16;
        ASSISTANT_FIRST_CAFE_DATE_DIALOG_ID = 17;
        ASSISTANT_UNLOCK_BASIC_DANCE_DIALOG_ID = 18;
        ASSISTANT_UNLOCK_CLOSER_DANCE_DIALOG_ID = 19;
        ASSISTANT_UNLOCK_TOPLESS_DANCE_DIALOG_ID = 20;
        ASSISTANT_UNLOCK_POSE_NAKED_DIALOG_ID = 21;
        ASSISTANT_UNLOCK_SOLO_FINGERING_DIALOG_ID = 22;
        ASSISTANT_UNLOCK_TOYS_MASTURBATION_DIALOG_ID = 23;

        ASSISTANT_UNLOCK_TENNIS_DATE_DIALOG_ID = 24;
        ASSISTANT_BAR_DATE_FIRST_VIDEO_UNLOCK_DIALOG_ID = 25;
        ASSISTANT_BAR_DATE_FIRST_VIDEO_UNLOCK_PART_2_DIALOG_ID = 26;
        ASSISTANT_DATE_VIDEO_TOKEN_AVAILABLE_DIALOG_ID = 27;



        ASSISTANT_BAR_DATE_SECOND_VIDEO_UNLOCK_DIALOG_ID = 28;
        ASSISTANT_BAR_DATE_SECOND_VIDEO_UNLOCK_PART_2_DIALOG_ID = 29;
        ASSISTANT_BAR_DATE_THIRD_VIDEO_UNLOCK_DIALOG_ID = 30;
        ASSISTANT_BAR_DATE_THIRD_VIDEO_UNLOCK_PART_2_DIALOG_ID = 31;
        ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_DIALOG_ID = 32;
        ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_PART_2_DIALOG_ID = 33;
        ASSISTANT_BAR_DATE_FOURTH_VIDEO_UNLOCK_PART_3_DIALOG_ID = 34;
        ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_DIALOG_ID = 35;
        ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_PART_2_DIALOG_ID = 36;
        ASSISTANT_BAR_DATE_FIFTH_VIDEO_UNLOCK_PART_3_DIALOG_ID = 37;

        ASSISTANT_UNLOCK_HANDJOB_DIALOG_ID = 38;
        ASSISTANT_UNLOCK_FOOTJOB_DIALOG_ID = 39;
        ASSISTANT_UNLOCK_TITSJOB_DIALOG_ID = 40;

        CRIME_SERVICE_TUTORIAL_DIALOG_ID = 200;
        CRIME_SERVICE_TUTORIAL_DIALOG_CLOSE_ID = 201;

        CRIME_SERVICE_SELECT_FEW_ID = 0;
        CRIME_SERVICE_GIFTS_CIGARETTES_ID = 1;
        CRIME_SERVICE_GIFTS_CONDOMS_ID = 2;
        CRIME_SERVICE_GIFTS_DRINKS_ID = 3;
        CRIME_SERVICE_GIFTS_DRUGS_ID = 4;
        CRIME_SERVICE_PATRONAGE_ID = 5;
        CRIME_SERVICE_NEGOTIATOR_ID = 6;
        CRIME_SERVICE_LOTTERY_ID = 7;
        CRIME_SERVICE_COACH_ID = 8;
        CRIME_SERVICE_RELAXER_ID = 9;

        SELECT_FEW_QUALITY_MULTIPLIER = 0.5f;
        PATRONAGE_CHANCE_MULTIPLIER = 0.3f; //The lower it is, the better
        NEGOTIATOR_MAX_USAGE = 1;
        NEGOTIATOR_PER_USAGE_MULTIPLIER = 5;
        COACH_EARNINGS_MULTIPLIER = 1.25f;
        COACH_ENERGY_LOST_MULTIPLIER = 1.25f;
        RELAXER_EARNINGS_MULTIPLIER = 0.75f;
        RELAXER_ENERGY_LOST_MULTIPLIER = 0.75f;

        FIRST_LATE_NIGHT_MEETING_DAY = 10;
 
        SECOND_LATE_NIGHT_MEETING_DAY_DELAY = 2;

        DATE_GAME_TIME = 45f;

        DATE_GAME_MAX_SCORE = 30;
        DATE_GAME_MAX_SCORE_INCREASE = 5;

        DATE_GAME_MIN_EARNT_SCORE = 5;

        DATE_GAME_MAX_HP = 3;

        CAFE_DATE_ID = 1;

        MONEY_TO_NICOLE_POINTS_CONVERSION_VALUE = 1000;

        MINIMUM_POINTS_EARNED_PER_DATE = 5;
        MINIMUM_POINTS_KEPT_PER_DATE = 5;
        MINIMUM_POINTS_EARNED_PER_DATE_INCREASE = 5;

        MINIMUM_DATES_PER_DAY = 1;

        PERSONAL_IMPROVEMENT_STORE_LEVEL = 0;

        DATE_GAME_SPEED_MULTIPLIER = 1f;
        DATE_GAME_SPEED_MULTIPLIER_MODIFIER = 0.05f;

        DATE_GAME_BETTER_SCORE_OBSTACLE_VALUE = 2;
        DATE_GAME_SCORE_STREAK_TO_REACH_FOR_VIDEO_TOKEN = 9;

    }

}


public class GMGlobalNumericVariables
{
    public static GlobalNumericVariables gnv = new GlobalNumericVariables();
}
