using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public static class StaticNumbers
{
    /*
    //WHEN ADDING A STATIC VARIABLE, DO NOT FORGET TO ADD IT IN THE RESETTER AND IN THE SAVE TOO !!!!!!!
    //MODIFY ONLY IN THE RESETTER !!!

    public static float STARTING_EARN_MONEY_GENERIC_MULTIPLIER = 1f;
    public static float STARTING_CURRENT_CLIENT_GENERATOR_TIMER = 10f;
    public static float STARTING_REPUTATION_GAIN = 1f;
    public static float STARTING_TRAINING_MULTIPLIER = 1f;
    public static int STARTING_REST_ENERGY_GAIN = 25;
    public static int STARTING_BASIC_NUMBER_OF_BOOTHS = 2;
    public static float STARTING_ASK_HELP_BONUS_MULTIPLIER = 1f;

    public static float STARTING_EARN_MONEY_DRINK_HAPPINESS_BOOST = 20f;
    public static float STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST = 20f;
    public static float STARTING_EARN_MONEY_DRUG_HAPPINESS_BOOST = 20f;
    public static float STARTING_EARN_MONEY_CONDOM_HAPPINESS_BOOST = 20f;


    public static int STARTING_MONEY = 300;
    public static float STARTING_REPUTATION = 0f;
    public static float STARTING_INFLUENCE = 0f;
    public static float STARTING_CONNECTION = 0f;
    public static int STARTING_DAY = 1;


    public static int BASIC_DAY_COST = 10;
    public static float DAY_COST_RANDOM_RANGE_PERCENTAGE = 10f;

    public static int BASIC_DAY_EARNINGS = 5;
    public static float DAY_EARNINGS_RANDOM_RANGE_PERCENTAGE = 50f;

    public static float BOOTH_GAME_TIMER_HELP = 5f;
    public static float BOOTH_GAME_TIMER_HELP_RANDOM_RANGE = 3f;
    public static float BOOTH_GAME_BASIC_BOOTH_TIME = 20f;
    public static int BOOTH_GAME_WORK_XP_VALUE = 1;
    public static int BOOTH_GAME_WORK_XP_RANDOM_RANGE_MIN = 0;
    public static int BOOTH_GAME_WORK_XP_RANDOM_RANGE_MAX = 10;
    public static int BOOTH_GAME_WORK_XP_RANDOM_RANGE_VALUE_TO_REACH = 9;

    public static float BOOTH_GAME_MIN_HAPPINESS_FOR_EXTEND = 60f;

    public static float BOOTH_GAME_TIME = 60f;

    public static int NUMBER_OF_BOOTHS = STARTING_BASIC_NUMBER_OF_BOOTHS;
    public static int MAX_NUMBER_OF_BOOTHS = 6;

    public static float CURRENT_CLIENT_GENERATOR_TIMER = STARTING_CURRENT_CLIENT_GENERATOR_TIMER;
    public static float BASIC_CLIENT_GENERATOR_RANDOM_RANGE = 2f;

    public static float ASK_HELP_TIMER = 10f;

    public static float EARN_MONEY_TIMER = 1f;
    public static int EARN_MONEY_DANCE_AMOUNT = 12;
    public static int EARN_MONEY_POSE_AMOUNT = 13;
    public static int EARN_MONEY_FOREPLAY_AMOUNT = 14;
    public static int EARN_MONEY_ORAL_AMOUNT = 15;
    public static int EARN_MONEY_SEX_AMOUNT = 16;
    public static int EARN_MONEY_GROUP_AMOUNT = 17;

    public static int EARN_MONEY_DANCE_INCREASE = 1;
    public static int EARN_MONEY_POSE_INCREASE = 1;
    public static int EARN_MONEY_FOREPLAY_INCREASE = 1;
    public static int EARN_MONEY_ORAL_INCREASE = 1;
    public static int EARN_MONEY_SEX_INCREASE = 1;
    public static int EARN_MONEY_GROUP_INCREASE = 1;

    public static float EARN_MONEY_HAPPINESS_MULTIPLIER = 0.1f;
    public static float EARN_MONEY_POPULARITY_MULTIPLIER = 0.1f;
    public static float EARN_MONEY_VERY_POOR_CLIENT_MULTIPLIER = 0.4f;
    public static float EARN_MONEY_POOR_CLIENT_MULTIPLIER = 0.6f;
    public static float EARN_MONEY_BELOW_AVERAGE_CLIENT_MULTIPLIER = 0.8f;
    public static float EARN_MONEY_AVERAGE_CLIENT_MULTIPLIER = 1f;
    public static float EARN_MONEY_ABOVE_AVERAGE_CLIENT_MULTIPLIER = 1.2f;
    public static float EARN_MONEY_RICH_CLIENT_MULTIPLIER = 1.4f;
    public static float EARN_MONEY_VERY_RICH_CLIENT_MULTIPLIER = 1.6f;
    public static float EARN_MONEY_MEGA_RICH_CLIENT_MULTIPLIER = 2f;
    public static float EARN_MONEY_CORRECT_FINISHER_MULTIPLIER = 5f;
    public static float EARN_MONEY_GIRL_ENERGY_LOST = 1f;
    public static float EARN_MONEY_GIRL_ENERGY_LOST_MODIFICATOR = 0.1f;
    public static float EARN_MONEY_GIRL_CUT_MULTIPLIER = 0.1f;

    public static float EARN_MONEY_GIRL_SKILL_MULTIPLIER = 0.15f;

    public static int EARN_MONEY_GIRL_POPULARITY_GAIN = 1;

    public static float EARN_MONEY_GENERIC_MULTIPLIER = STARTING_EARN_MONEY_GENERIC_MULTIPLIER;

    public static float EARN_MONEY_DRINK_HAPPINESS_BOOST = STARTING_EARN_MONEY_DRINK_HAPPINESS_BOOST;
    public static float EARN_MONEY_FOOD_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;
    public static float EARN_MONEY_DRUG_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;
    public static float EARN_MONEY_CONDOM_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;

    public static float IMPROVEMENT_HAPPINESS_BOOST = 5f;

    public static float EARN_OPENNESS_TIMER = 1f;
    public static float EARN_OPENNESS_AMOUNT = 0.07f;

    public static int INFLUENCE_GAIN = 1;
    public static int CONNECTION_GAIN = 1;
    public static int INFLUENCE_LOST = 1;
    public static int CONNECTION_LOST = 1;

    public static float BASIC_REPUTATION_GAIN = 1f;
    public static float REPUTATION_GAIN = STARTING_REPUTATION_GAIN;

    public static float CLIENT_HAPPINESS_INCREASE_MULTIPLIER = 0.025f;

    public static float CLIENT_END_WITHOUT_GIRL_POPULARITY_DROP = 5f;
    public static int CLIENT_CORRECT_HELP_HAPPINESS_BOOST = 20;
    public static int CLIENT_INCORRECT_HELP_HAPPINESS_LOST = 20;
    public static float CLIENT_BASE_HAPPINESS_GAIN = 0.1f;
    public static float CLIENT_CREATION_HAPPINESS_MIN = 40f;
    public static float CLIENT_CREATION_HAPPINESS_MAX = 60f;

    public static int REPUTATION_MIN = 0;
    public static int REPUTATION_MAX = 100;

    public static float BASIC_DANCE_POLICIES_MULTIPLIER = 1f;
    public static float DANCE_POLICIES_MULTIPLIER = BASIC_DANCE_POLICIES_MULTIPLIER;
    public static float DANCE_POLICIES_INCREASE = 0.1f;

    public static float BASIC_POSE_POLICIES_MULTIPLIER = 1f;
    public static float POSE_POLICIES_MULTIPLIER = BASIC_POSE_POLICIES_MULTIPLIER;
    public static float POSE_POLICIES_INCREASE = 0.1f;

    public static float BASIC_FOREPLAY_POLICIES_MULTIPLIER = 1f;
    public static float FOREPLAY_POLICIES_MULTIPLIER = BASIC_FOREPLAY_POLICIES_MULTIPLIER;
    public static float FOREPLAY_POLICIES_INCREASE = 0.1f;

    public static float BASIC_ORAL_POLICIES_MULTIPLIER = 1f;
    public static float ORAL_POLICIES_MULTIPLIER = BASIC_ORAL_POLICIES_MULTIPLIER;
    public static float ORAL_POLICIES_INCREASE = 0.1f;

    public static float BASIC_SEX_POLICIES_MULTIPLIER = 1f;
    public static float SEX_POLICIES_MULTIPLIER = BASIC_SEX_POLICIES_MULTIPLIER;
    public static float SEX_POLICIES_INCREASE = 0.1f;

    public static float BASIC_GROUP_POLICIES_MULTIPLIER = 1f;
    public static float GROUP_POLICIES_MULTIPLIER = BASIC_GROUP_POLICIES_MULTIPLIER;
    public static float GROUP_POLICIES_INCREASE = 0.1f;

    public static float BASIC_FACIAL_POLICIES_MULTIPLIER = 1f;
    public static float FACIAL_POLICIES_MULTIPLIER = BASIC_FACIAL_POLICIES_MULTIPLIER;
    public static float FACIAL_POLICIES_INCREASE = 0.1f;

    public static float BASIC_BODY_POLICIES_MULTIPLIER = 1f;
    public static float BODY_POLICIES_MULTIPLIER = BASIC_BODY_POLICIES_MULTIPLIER;
    public static float BODY_POLICIES_INCREASE = 0.1f;

    public static float BASIC_INSIDE_POLICIES_MULTIPLIER = 1f;
    public static float INSIDE_POLICIES_MULTIPLIER = BASIC_INSIDE_POLICIES_MULTIPLIER;
    public static float INSIDE_POLICIES_INCREASE = 0.1f;

    public static float CHANCE_CLIENT_IS_CRIMINAL = 0.1f;
    public static float CHANCE_CLIENT_IS_POLICE = 0.1f;

    public static int NEW_BOOTH_PRICE = 100;
    public static int BAR_PRICE = 100;
    public static int KITCHEN_PRICE = 100;
    public static int PHARMACY_PRICE = 100;
    public static int CONDOM_DISPENSERS_PRICE = 100;
    public static int STAGE_PRICE = 100;
    public static int TRAINING_ZONE_PRICE = 100;
    public static int TRAINING_ZONE_DANCE_PRICE = 100;
    public static int TRAINING_ZONE_POSE_PRICE = 100;
    public static int TRAINING_ZONE_FOREPLAY_PRICE = 100;
    public static int TRAINING_ZONE_ORAL_PRICE = 100;
    public static int TRAINING_ZONE_SEX_PRICE = 100;
    public static int TRAINING_ZONE_GROUP_PRICE = 100;
    public static int DRESSING_ROOM_PRICE = 100;
    public static int DRESSING_ROOM_PILLOWS_PRICE = 100;
    public static int DRESSING_ROOM_LOUNGE_CHAIR_PRICE = 100;
    public static int DRESSING_ROOM_COUCH_PRICE = 100;
    public static int DRESSING_ROOM_BED_PRICE = 100;
    public static int DRESSING_ROOM_KING_SIZE_BED_PRICE = 100;
    public static int SIGN_PRICE = 100;
    public static int ON_LINE_ADS_CAMPAIGN_PRICE = 100;
    public static int FLYER_AD_CAMPAIGN_PRICE = 100;
    public static int LIVE_AD_CAMPAIGN_PRICE = 100;
    public static int SEXY_COSTUME_PRICE = 100;
    public static int BUNNY_COSTUME_PRICE = 100;
    public static int MAID_COSTUME_PRICE = 100;
    public static int NURSE_COSTUME_PRICE = 100;

    public static float BASIC_TRAINING_MULTIPLIER = 1f;
    public static float TRAINING_MULTIPLIER = STARTING_TRAINING_MULTIPLIER;
    public static float DANCE_TRAINING_MULTIPLIER = 0f;
    public static float POSE_TRAINING_MULTIPLIER = 0f;
    public static float FOREPLAY_TRAINING_MULTIPLIER = 0f;
    public static float ORAL_TRAINING_MULTIPLIER = 0f;
    public static float SEX_TRAINING_MULTIPLIER = 0f;
    public static float GROUP_TRAINING_MULTIPLIER = 0f;

    public static int REST_ENERGY_GAIN = STARTING_REST_ENERGY_GAIN;

    public static float BASIC_ASK_HELP_BONUS_MULTIPLIER = 1f;
    public static float ASK_HELP_BONUS_MULTIPLIER = STARTING_ASK_HELP_BONUS_MULTIPLIER;

    public static float MIN_OPENNESS_DANCE = 0f;
    public static float MIN_OPENNESS_POSE = 16.6f;
    public static float MIN_OPENNESS_FOREPLAY = 33.2f;
    public static float MIN_OPENNESS_ORAL = 49.8f;
    public static float MIN_OPENNESS_SEX = 66.4f;
    public static float MIN_OPENNESS_GROUP = 83f;

    public static float MIN_OPENNESS_BODY_FINISH = 66.4f;
    public static float MIN_OPENNESS_FACIAL_FINISH = 33.2f;
    public static float MIN_OPENNESS_INSIDE_FINISH = 71.9f;
    public static float MIN_OPENNESS_INSIDE_ANAL_FINISH = 83f;
    public static float MIN_OPENNESS_SWALLOW_FINISH = 49.8f;
    public static float MIN_OPENNESS_TITS_FINISH = 38.7f;

    public static int MAX_SAVE_SLOTS = 100;


    //The index of the scene currently being played in the tutorial
    //e.g. the scene 0 of the tutorial is on the club, the scene 1 is on the recruitment screen, etc...
    public static int TUTORIAL_SCENE_STEP_NUMBER = 0;

    public static float CLIENT_HAPPINESS_TRANSFER_RATIO = 0.04f;

    public static void Reset()
    {
        STARTING_EARN_MONEY_GENERIC_MULTIPLIER = 1f;
        STARTING_CURRENT_CLIENT_GENERATOR_TIMER = 10f;
        STARTING_REPUTATION_GAIN = 1f;
        STARTING_TRAINING_MULTIPLIER = 1f;
        STARTING_REST_ENERGY_GAIN = 25;
        STARTING_BASIC_NUMBER_OF_BOOTHS = 2;
        STARTING_ASK_HELP_BONUS_MULTIPLIER = 1f;

        STARTING_EARN_MONEY_DRINK_HAPPINESS_BOOST = 20f;
        STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST = 20f;
        STARTING_EARN_MONEY_DRUG_HAPPINESS_BOOST = 20f;
        STARTING_EARN_MONEY_CONDOM_HAPPINESS_BOOST = 20f;


        STARTING_MONEY = 300;
        STARTING_REPUTATION = 0f;
        STARTING_INFLUENCE = 0f;
        STARTING_CONNECTION = 0f;
        STARTING_DAY = 1;


        BASIC_DAY_COST = 10;
        DAY_COST_RANDOM_RANGE_PERCENTAGE = 10f;

        BASIC_DAY_EARNINGS = 5;
        DAY_EARNINGS_RANDOM_RANGE_PERCENTAGE = 50f;

        BOOTH_GAME_TIMER_HELP = 5f;
        BOOTH_GAME_TIMER_HELP_RANDOM_RANGE = 3f;
        BOOTH_GAME_BASIC_BOOTH_TIME = 20f;
        BOOTH_GAME_WORK_XP_VALUE = 1;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_MIN = 0;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_MAX = 10;
        BOOTH_GAME_WORK_XP_RANDOM_RANGE_VALUE_TO_REACH = 9;

        BOOTH_GAME_MIN_HAPPINESS_FOR_EXTEND = 60f;

        BOOTH_GAME_TIME = 60f;

        NUMBER_OF_BOOTHS = STARTING_BASIC_NUMBER_OF_BOOTHS;
        MAX_NUMBER_OF_BOOTHS = 6;

        CURRENT_CLIENT_GENERATOR_TIMER = STARTING_CURRENT_CLIENT_GENERATOR_TIMER;
        BASIC_CLIENT_GENERATOR_RANDOM_RANGE = 2f;

        ASK_HELP_TIMER = 10f;

        EARN_MONEY_TIMER = 1f;
        EARN_MONEY_DANCE_AMOUNT = 12;
        EARN_MONEY_POSE_AMOUNT = 13;
        EARN_MONEY_FOREPLAY_AMOUNT = 14;
        EARN_MONEY_ORAL_AMOUNT = 15;
        EARN_MONEY_SEX_AMOUNT = 16;
        EARN_MONEY_GROUP_AMOUNT = 17;

        EARN_MONEY_DANCE_INCREASE = 1;
        EARN_MONEY_POSE_INCREASE = 1;
        EARN_MONEY_FOREPLAY_INCREASE = 1;
        EARN_MONEY_ORAL_INCREASE = 1;
        EARN_MONEY_SEX_INCREASE = 1;
        EARN_MONEY_GROUP_INCREASE = 1;

        EARN_MONEY_HAPPINESS_MULTIPLIER = 0.1f;
        EARN_MONEY_POPULARITY_MULTIPLIER = 0.1f;
        EARN_MONEY_VERY_POOR_CLIENT_MULTIPLIER = 0.4f;
        EARN_MONEY_POOR_CLIENT_MULTIPLIER = 0.6f;
        EARN_MONEY_BELOW_AVERAGE_CLIENT_MULTIPLIER = 0.8f;
        EARN_MONEY_AVERAGE_CLIENT_MULTIPLIER = 1f;
        EARN_MONEY_ABOVE_AVERAGE_CLIENT_MULTIPLIER = 1.2f;
        EARN_MONEY_RICH_CLIENT_MULTIPLIER = 1.4f;
        EARN_MONEY_VERY_RICH_CLIENT_MULTIPLIER = 1.6f;
        EARN_MONEY_MEGA_RICH_CLIENT_MULTIPLIER = 2f;
        EARN_MONEY_CORRECT_FINISHER_MULTIPLIER = 2f;
        EARN_MONEY_GIRL_ENERGY_LOST = 1f;
        EARN_MONEY_GIRL_ENERGY_LOST_MODIFICATOR = 0.1f;
        EARN_MONEY_GIRL_CUT_MULTIPLIER = 0.1f;

        EARN_MONEY_GIRL_SKILL_MULTIPLIER = 0.15f;

        EARN_MONEY_GIRL_POPULARITY_GAIN = 1;

        EARN_MONEY_GENERIC_MULTIPLIER = STARTING_EARN_MONEY_GENERIC_MULTIPLIER;

        EARN_MONEY_DRINK_HAPPINESS_BOOST = STARTING_EARN_MONEY_DRINK_HAPPINESS_BOOST;
        EARN_MONEY_FOOD_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;
        EARN_MONEY_DRUG_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;
        EARN_MONEY_CONDOM_HAPPINESS_BOOST = STARTING_EARN_MONEY_FOOD_HAPPINESS_BOOST;

        IMPROVEMENT_HAPPINESS_BOOST = 5f;

        EARN_OPENNESS_TIMER = 1f;
        EARN_OPENNESS_AMOUNT = 0.07f;

        INFLUENCE_GAIN = 1;
        CONNECTION_GAIN = 1;
        INFLUENCE_LOST = 1;
        CONNECTION_LOST = 1;

        BASIC_REPUTATION_GAIN = 1f;
        REPUTATION_GAIN = STARTING_REPUTATION_GAIN;

        CLIENT_HAPPINESS_INCREASE_MULTIPLIER = 0.025f;

        CLIENT_END_WITHOUT_GIRL_POPULARITY_DROP = 5f;
        CLIENT_CORRECT_HELP_HAPPINESS_BOOST = 20;
        CLIENT_INCORRECT_HELP_HAPPINESS_LOST = 20;
        CLIENT_BASE_HAPPINESS_GAIN = 0.1f;
        CLIENT_CREATION_HAPPINESS_MIN = 40f;
        CLIENT_CREATION_HAPPINESS_MAX = 60f;

        REPUTATION_MIN = 0;
        REPUTATION_MAX = 100;

        BASIC_DANCE_POLICIES_MULTIPLIER = 1f;
        DANCE_POLICIES_MULTIPLIER = BASIC_DANCE_POLICIES_MULTIPLIER;
        DANCE_POLICIES_INCREASE = 0.1f;

        BASIC_POSE_POLICIES_MULTIPLIER = 1f;
        POSE_POLICIES_MULTIPLIER = BASIC_POSE_POLICIES_MULTIPLIER;
        POSE_POLICIES_INCREASE = 0.1f;

        BASIC_FOREPLAY_POLICIES_MULTIPLIER = 1f;
        FOREPLAY_POLICIES_MULTIPLIER = BASIC_FOREPLAY_POLICIES_MULTIPLIER;
        FOREPLAY_POLICIES_INCREASE = 0.1f;

        BASIC_ORAL_POLICIES_MULTIPLIER = 1f;
        ORAL_POLICIES_MULTIPLIER = BASIC_ORAL_POLICIES_MULTIPLIER;
        ORAL_POLICIES_INCREASE = 0.1f;

        BASIC_SEX_POLICIES_MULTIPLIER = 1f;
        SEX_POLICIES_MULTIPLIER = BASIC_SEX_POLICIES_MULTIPLIER;
        SEX_POLICIES_INCREASE = 0.1f;

        BASIC_GROUP_POLICIES_MULTIPLIER = 1f;
        GROUP_POLICIES_MULTIPLIER = BASIC_GROUP_POLICIES_MULTIPLIER;
        GROUP_POLICIES_INCREASE = 0.1f;

        BASIC_FACIAL_POLICIES_MULTIPLIER = 1f;
        FACIAL_POLICIES_MULTIPLIER = BASIC_FACIAL_POLICIES_MULTIPLIER;
        FACIAL_POLICIES_INCREASE = 0.1f;

        BASIC_BODY_POLICIES_MULTIPLIER = 1f;
        BODY_POLICIES_MULTIPLIER = BASIC_BODY_POLICIES_MULTIPLIER;
        BODY_POLICIES_INCREASE = 0.1f;

        BASIC_INSIDE_POLICIES_MULTIPLIER = 1f;
        INSIDE_POLICIES_MULTIPLIER = BASIC_INSIDE_POLICIES_MULTIPLIER;
        INSIDE_POLICIES_INCREASE = 0.1f;

        CHANCE_CLIENT_IS_CRIMINAL = 0.1f;
        CHANCE_CLIENT_IS_POLICE = 0.1f;

        NEW_BOOTH_PRICE = 100;
        BAR_PRICE = 100;
        KITCHEN_PRICE = 100;
        PHARMACY_PRICE = 100;
        CONDOM_DISPENSERS_PRICE = 100;
        STAGE_PRICE = 100;
        TRAINING_ZONE_PRICE = 100;
        TRAINING_ZONE_DANCE_PRICE = 100;
        TRAINING_ZONE_POSE_PRICE = 100;
        TRAINING_ZONE_FOREPLAY_PRICE = 100;
        TRAINING_ZONE_ORAL_PRICE = 100;
        TRAINING_ZONE_SEX_PRICE = 100;
        TRAINING_ZONE_GROUP_PRICE = 100;
        DRESSING_ROOM_PRICE = 100;
        DRESSING_ROOM_PILLOWS_PRICE = 100;
        DRESSING_ROOM_LOUNGE_CHAIR_PRICE = 100;
        DRESSING_ROOM_COUCH_PRICE = 100;
        DRESSING_ROOM_BED_PRICE = 100;
        DRESSING_ROOM_KING_SIZE_BED_PRICE = 100;
        SIGN_PRICE = 100;
        ON_LINE_ADS_CAMPAIGN_PRICE = 100;
        FLYER_AD_CAMPAIGN_PRICE = 100;
        LIVE_AD_CAMPAIGN_PRICE = 100;
        SEXY_COSTUME_PRICE = 100;
        BUNNY_COSTUME_PRICE = 100;
        MAID_COSTUME_PRICE = 100;
        NURSE_COSTUME_PRICE = 100;

        BASIC_TRAINING_MULTIPLIER = 1f;
        TRAINING_MULTIPLIER = STARTING_TRAINING_MULTIPLIER;
        DANCE_TRAINING_MULTIPLIER = 0f;
        POSE_TRAINING_MULTIPLIER = 0f;
        FOREPLAY_TRAINING_MULTIPLIER = 0f;
        ORAL_TRAINING_MULTIPLIER = 0f;
        SEX_TRAINING_MULTIPLIER = 0f;
        GROUP_TRAINING_MULTIPLIER = 0f;

        REST_ENERGY_GAIN = STARTING_REST_ENERGY_GAIN;

        BASIC_ASK_HELP_BONUS_MULTIPLIER = 1f;
        ASK_HELP_BONUS_MULTIPLIER = STARTING_ASK_HELP_BONUS_MULTIPLIER;

        MIN_OPENNESS_DANCE = 0f;
        MIN_OPENNESS_POSE = 16.6f;
        MIN_OPENNESS_FOREPLAY = 33.2f;
        MIN_OPENNESS_ORAL = 49.8f;
        MIN_OPENNESS_SEX = 66.4f;
        MIN_OPENNESS_GROUP = 83f;

        MIN_OPENNESS_BODY_FINISH = 66.4f;
        MIN_OPENNESS_FACIAL_FINISH = 33.2f;
        MIN_OPENNESS_INSIDE_FINISH = 71.9f;
        MIN_OPENNESS_INSIDE_ANAL_FINISH = 83f;
        MIN_OPENNESS_SWALLOW_FINISH = 49.8f;
        MIN_OPENNESS_TITS_FINISH = 38.7f;

        MAX_SAVE_SLOTS = 100;


        //The index of the scene currently being played in the tutorial
        //e.g. the scene 0 of the tutorial is on the club, the scene 1 is on the recruitment screen, etc...
        TUTORIAL_SCENE_STEP_NUMBER = 0;

        CLIENT_HAPPINESS_TRANSFER_RATIO = 0.04f;
    }
    */
}
